version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: motion_detection_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: motion_detection_system
    networks:
      - motion_detection_network

  # 可選：MongoDB 管理界面
  mongo-express:
    image: mongo-express:latest
    container_name: motion_detection_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - motion_detection_network

volumes:
  mongodb_data:

networks:
  motion_detection_network:
    driver: bridge
